keys:
  - &users:
    - &biscotty age180emxd4x6f7glg8swp2paxvt0c89am5vu79ecwwdza0fqedwv3lqf5524m
  - &hosts:
    - &nixos age1yy9pmcj3lyrgm5pdy4u0d8gn327yy5m89z63j03td09gvmywj4gsvx2lc3
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
    - age:
      - *biscotty
      - *nixos
