{ config, pkgs, ... }:

{

  environment.systemPackages = with pkgs; [
    kdePackages.qtmultimedia
    sddm-astronaut
    aaxtomp3
    air-formatter
    appimage-run
    ascii-image-converter
    atool
    audible-cli
    bartib
    bat
    bluez
    bottom
    btop
    cachix
    catimg
    ccl
    chroma
    curl
    ddgr
    devenv
    distrobox
    dive
    djvulibre
    dropbox
    exiftool
    fastfetch
    fd
    feh
    ffmpeg
    ffmpegthumbnailer
    flatpak
    fzf
    gdu
    gephi
    gh
    ghostscript
    git
    gocryptfs
    gv
    httpie-desktop
    ihp-new
    imagemagick
    inetutils
    jq
    kitty
    lazygit
    libarchive
    libqalculate
    librsvg
    libsForQt5.kparts
    lsd
    mdcat
    mediainfo
    mlocate
    mpv
    mupdf
    neovim
    net-tools
    nethogs
    nh
    nix-output-monitor
    nixfmt
    odt2txt
    opentabletdriver
    p7zip
    pandoc
    pastel
    pcre2
    perl
    pixcat
    podman
    podman-tui
    poppler-utils
    pycritty
    python313Packages.python-lsp-ruff
    python313Packages.python-lsp-server
    qalculate-qt
    qemu
    restic
    ripgrep
    ripgrep-all
    ruff
    sddm-astronaut
    sqlite
    sqlite-utils
    starship
    stow
    surfraw
    tcpdump
    tldr
    ueberzugpp
    unrar
    unzip
    vim-full # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
    vlc
    w3m
    wayland-protocols
    wayland-utils
    wget
    wl-clipboard
    wlroots
    xclip
    xdg-desktop-portal-gtk
    xdg-utils
    xlsx2csv
    xsel
    xwayland
    yazi
    zathura
    zoxide
    kdePackages.fcitx5-with-addons
    kdePackages.karousel
    kdePackages.kcolorchooser
    kdePackages.kparts
    kdePackages.parley
    kdePackages.sddm
  ];

}
