{ config, pkgs, ... }:

{

  environment.systemPackages = with pkgs; [
    pycritty
    yazi
    air-formatter
    nixfmt
    ccl
    lsd
    audible-cli
    aaxtomp3
    neovim
    kdePackages.kcolorchooser
    pcre2
    ascii-image-converter
    kdePackages.kparts
    libsForQt5.kparts
    sqlite
    ghostscript
    gv
    sqlite-utils
    perl
    exiftool
    libarchive
    odt2txt
    librsvg
    xlsx2csv
    jq
    starship
    xclip
    xsel
    xwayland
    wayland-protocols
    wayland-utils
    wl-clipboard
    wlroots
    chroma
    pixcat
    kitty
    lazygit
    qalculate-qt
    appimage-run
    alacritty-theme
    devenv
    opentabletdriver
    ihp-new
    googleearth-pro
    fastfetch
    pastel
    libqalculate
    zathura
    gocryptfs
    fd
    dropbox
    httpie-desktop
    discordo
    mpv
    mupdf
    poppler-utils
    atool
    p7zip
    unrar
    mediainfo
    djvulibre
    ffmpeg
    ffmpegthumbnailer
    nh
    w3m
    mlocate
    mdcat
    inetutils
    net-tools
    tcpdump
    nethogs
    gdu
    ddgr
    surfraw
    bartib
    unzip
    ripgrep-all
    distrobox
    bat
    ripgrep
    curl
    btop
    wget
    bottom
    zellij
    tldr
    flatpak
    fzf
    feh
    imagemagick
    vim-full # Do not forget to add an editor to edit configuration.nix! The Nano editor is also installed by default.
    git
    alacritty
    restic
    xdg-desktop-portal-gtk
    xdg-utils
    qemu
    mlocate
    dive
    cachix
    sddm-chili-theme
    podman
    helix
    podman-tui
    ueberzugpp
    kdePackages.sddm
    kdePackages.parley
    kdePackages.fcitx5-with-addons
    sddm-sugar-dark
    sops
    python313Packages.python-lsp-server
    python313Packages.python-lsp-ruff
    ruff
    #python312Packages.jedi-language-server
    stow
    vlc
    gh
    catimg
    gephi
    ueberzugpp
    pandoc
    zoxide
  ];

}
